import { ConvexAuthProvider } from "@convex-dev/auth/react";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import {Toaster} from "@/components/ui/sonner"
import { Modals } from "@/components/modal";
import { JotaiProvider } from "@/components/jotai";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Slack Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
    <html lang="en">
      <body className={inter.className}>

        <ConvexClientProvider >
          <JotaiProvider>
         <Toaster/>
          <Modals/>
        {children}
        </JotaiProvider>
        </ConvexClientProvider>
      </body>
    </html>
    </ConvexAuthNextjsServerProvider>
  );
}
